### ISSUE TITLE
Failing on 9.81 and 10.15

### ISSUE THREAD

**Issue by sooheon** [alex314159/ib-re-actor-976-plus#5]
Tried with both versions available currently, they fail for different reasons. 

9.81:

```
Syntax error compiling at (ib_re_actor_976_plus/translation.clj:110:1).
Unable to find static field: CRYPTO in class com.ib.client.Types$SecType
```

10.15:

```
Syntax error (IllegalArgumentException) compiling reify* at (ib_re_actor_976_plus/wrapper.clj:185:25).
Can't define method not in interfaces: error
```

(I've made sure to rename and add the `EWrapper_10.15.02.java` file to resources of my local project, so that `ewrapper-java-methods` doesn't fall back to older version)

**Comment by alex314159** [comment]
Thanks for this.

Maybe I wasn't so good at backwards compatibility. For 9.81 try removing the CRYPTO security type, IB added it only recently. But there may be other funnies, like BigDecimal instead of int.

For 10.15 I'll have to investigate this week-end. I'm using 10.11.01 live atm and it works so if you can get hold of that tws jar suggest you try this.

**Comment by sooheon** [comment]
Got ya. Even though it wasn't visible on site, I did find it at this url : https://interactivebrokers.github.io/downloads/twsapi_macunix.1011.01.zip

WHo knows how long it'll stay up, they don't seem to have the older ones.

**Comment by alex314159** [comment]
They changed the signature of one of the error functions, which need to be manually specified as overloaded.
Your first error function in wrapper.clj should now be:
```
(list (quote ^void error) [(quote this) (quote ^int id) (quote ^int errorCode) (quote ^String errorMsg) (quote ^String advancedOrderRejectJson)]
           (list dispatch-message (quote cb) {:type :error :id (quote id) :code (quote errorCode) :message (quote errorMsg) :advanced-order-reject-json (quote advancedOrderRejectJson)}))
```

This compiles, but I'll test a little bit over the week-end to make sure no other breaking issues before releasing.

**Comment by sooheon** [comment]
How did you debug this? Did you just read through the diff of their source code?

**Comment by alex314159** [comment]
yes, pretty much. The message you got was actually quite explicit "Can't define method not in interfaces: error" and I knew the error methods in the wrapper are a special case that gave me lots of pain initially as they're overloaded. Thanks again for flagging!

**Comment by alex314159** [comment]
Should be sorted in 0.1.7-SNAPSHOT. Obviously test at length using a paper account!
